spring.datasource:
  url: jdbc:mysql://localhost/books?autoReconnect=true&characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password: root

management.endpoints.web.exposure.include: "*"

spring.boot.admin.client.url: "http://localhost:8080"
server:
  port: 8081
